apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recommendation
    version: v3
  name: recommendation-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
      version: v3
  template:
    metadata:
      labels:
        app: recommendation
        version: v3
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        image: quay.io/maistra_demos/recommendation:v3
        imagePullPolicy: Always
        name: recommendation
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
