apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation-retries
spec:
  hosts:
    - recommendation
  http:
    - route:
        - destination:
            host: recommendation
      retries:
        attempts: 10
        perTryTimeout: 2s