apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: preferencewhitelist
spec:
  compiledAdapter: listchecker
  params:
    overrides: ["v1", "v3"]
    blacklist: false
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: preferencesource
spec:
  compiledTemplate: listentry
  params:
    value: destination.labels["version"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: checktorecommendation
spec:
  match: destination.labels["app"] == "recommendation"
  actions:
  - handler: preferencewhitelist
    instances: [ preferencesource ]
